Docker block
skills/publish-packages pull request #22
Opened 2023-04-25 06:04 UTC by sinsukehlab

### Why:

nginx:1.17 is vulnerable.

### What's being changed:

README.md
- comment: CC-BY 4.0 &rarr; MIT
- Dockerfile block: nginx:1.17 &rarr; nginx:1.24-alpine
- Add `-p 8080:80` to the `docker run` command

### Check off the following:

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2023-04-25 18:33 UTC, hectorsector requested changes
Thanks for making the update @sinsukehlab! We'll also need to update the workflow for step 2 (see below) as it validates the contents of `Dockerfile`. 

To test your changes after you do this, you can:
1. Create a new repository
2. Push from your branch to the new repository's `main` branch
3. Run through the course in the new repository

These steps should flag any remaining problems with the changes. 

https://github.com/skills/publish-packages/blob/530a46efc646ae7d6e0739953b6cb93055143723/.github/workflows/2-add-a-dockerfile.yml#L61-L66

2023-05-01 07:16 UTC, sinsukehlab commented
The workflow verified
https://github.com/sinsukehlab/publish-packages-sinsukehlab/actions/runs/4817443439

2023-05-02 16:11 UTC, cmwilson21 commented
@sinsukehlab Thanks for the verification! I'll take a look at this from the content side ✨

2023-05-09 21:17 UTC, cmwilson21 commented on README.md
> +1. Enter the Personal Access Token you just created as the Password.
```suggestion
1. Enter your new Personal Access Token as the password.
```
I think this line could be trimmed down just a little.

2023-05-09 21:18 UTC, cmwilson21 commented on README.md
> +   ![example of running the docker command listed above](https://user-images.githubusercontent.com/3250463/219255534-f11b20e8-65de-4f4a-a033-f312ddf507fb.png)<!-- This screenshot should be changed. -
```suggestion

```
Could we just remove the image?

2023-05-09 21:25 UTC, cmwilson21 commented on README.md
> +1. (optional) You can open [localhost:8080](http://localhost:8080) to see the page you just created.
```suggestion
1. Optionally, you can open [localhost:8080](http://localhost:8080) to see the page you just created.
```

2023-05-09 21:26 UTC, cmwilson21 commented
@sinsukehlab 👋 - Just added a few minor content edits 👍 

Let me know if you accept them and I'll get this merged ✅

2023-05-11 05:13 UTC, sinsukehlab commented
@cmwilson21 Thanks for adding the edits. I have accepted them.

2023-05-11 19:36 UTC, cmwilson21 approved these changes
LGTM! Thanks for the updates! 🎉

2023-05-23 06:20 UTC, sinsukehlab commented
@cmwilson21 @hectorsector gentle reminder

2023-05-23 15:47 UTC, hectorsector approved these changes
Thanks for your patience @sinsukehlab!

2023-05-23 15:48 UTC, merged